// <auto-generated />
namespace TodoList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class insert__lists : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(insert__lists));
        
        string IMigrationMetadata.Id
        {
            get { return "202312040529444_insert__lists"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
